import fs from "node:fs";
import path from "node:path";
import chalk from "chalk";
import { getBundledKitPath } from "../kit/loader.js";
import { findKitInRegistry } from "../kit/registry.js";
import {
  SUPERDUPER_DIR,
  DESIGN_MD_FILE,
  KIT_MANIFEST_FILE,
} from "../kit/types.js";

const TEMPLATE_DESIGN_MD = `# Design System

> Generated by SuperDuper AI Studio CLI.
> Edit this file to describe your design system, then run your AI coding agent.

## Colours

| Token | Value | Usage |
|-------|-------|-------|
| --color-primary | #6366F1 | Primary actions, links |
| --color-background | #FFFFFF | Page background |
| --color-foreground | #111111 | Body text |

## Typography

- **Font family:** Inter, system-ui, sans-serif
- **Base size:** 16px
- **Scale:** 1.25 (Major Third)

## Spacing

4px base unit. Use multiples: 4, 8, 12, 16, 24, 32, 48, 64.

## Components

Document your key components here. Each component should include:
- Name and description
- Token usage
- Code example
`;

export async function initCommand(options: {
  kit?: string;
}): Promise<void> {
  const targetDir = path.join(process.cwd(), SUPERDUPER_DIR);

  if (fs.existsSync(targetDir)) {
    console.log(
      chalk.yellow("Warning:"),
      `.superduper/ already exists in this directory.`
    );
    console.log(`Use ${chalk.cyan("superduperui-context use <kit>")} to switch kits.`);
    return;
  }

  if (options.kit) {
    await initWithKit(options.kit, targetDir);
  } else {
    await initBlank(targetDir);
  }

  console.log();
  console.log(chalk.bold("Next steps:"));
  console.log();
  console.log(
    `  ${chalk.dim("1.")} Edit ${chalk.cyan(`.superduper/${DESIGN_MD_FILE}`)} with your design system`
  );
  console.log(
    `  ${chalk.dim("2.")} Add the MCP server to your AI coding agent:`
  );
  console.log();
  console.log(chalk.dim("  Claude Code (claude_desktop_config.json):"));
  console.log(
    chalk.gray(
      `    { "mcpServers": { "design": { "command": "npx", "args": ["@superduperui/context", "serve"] } } }`
    )
  );
  console.log();
  console.log(chalk.dim("  Cursor (.cursor/mcp.json):"));
  console.log(
    chalk.gray(
      `    { "mcpServers": { "design": { "command": "npx", "args": ["@superduperui/context", "serve"] } } }`
    )
  );
}

async function initWithKit(kitName: string, targetDir: string): Promise<void> {
  // Check bundled kits first
  const bundledPath = getBundledKitPath(kitName);

  if (bundledPath) {
    fs.cpSync(bundledPath, targetDir, { recursive: true });
    console.log(
      chalk.green("✓"),
      `Initialised .superduper/ with the ${chalk.bold(kitName)} kit.`
    );
    return;
  }

  // Check registry
  const registryEntry = findKitInRegistry(kitName);

  if (registryEntry) {
    if (registryEntry.tier === "pro") {
      console.log(
        chalk.yellow("Pro kit:"),
        `${chalk.bold(registryEntry.displayName)} is a premium kit (${chalk.yellow(registryEntry.price ?? "paid")}).`
      );
      console.log();
      console.log(
        `  Purchase at ${chalk.cyan("https://superduperui.com/kits/" + kitName)}`
      );
      console.log(
        `  Then import with: ${chalk.cyan(`superduperui-context import <path-to-zip>`)}`
      );
      return;
    }

    // Free registry kit that isn't bundled — shouldn't happen but handle gracefully
    console.log(
      chalk.red("Error:"),
      `Kit "${kitName}" is listed in the registry but not bundled. This may be a packaging issue.`
    );
    return;
  }

  console.log(
    chalk.red("Error:"),
    `Kit "${kitName}" not found.`
  );
  console.log(
    `Run ${chalk.cyan("superduperui-context list")} to see available kits.`
  );
}

async function initBlank(targetDir: string): Promise<void> {
  fs.mkdirSync(targetDir, { recursive: true });

  const manifest = {
    name: "custom",
    version: "1.0.0",
    displayName: "Custom",
    description: "Your custom design system",
    source: "manual",
    tier: "free",
    tokenCount: 0,
    componentCount: 0,
    aesthetic: "",
  };

  fs.writeFileSync(
    path.join(targetDir, KIT_MANIFEST_FILE),
    JSON.stringify(manifest, null, 2) + "\n"
  );
  fs.writeFileSync(
    path.join(targetDir, DESIGN_MD_FILE),
    TEMPLATE_DESIGN_MD
  );

  console.log(
    chalk.green("✓"),
    "Initialised .superduper/ with a blank design system template."
  );
}
